using System;

public enum BattleType{Wild,Trainer}


public enum StatName{HEALTH,MANA,PHYSICAL,MAGIC,MANAREGEN,DODGE,LUCK}
public enum StatusEffects{POISON,PARASITE,HOLYWATER,SHIELD,SHIELDBREAK,WOUND}
public enum Zodiac{ARIES,TAURUS,GEMINI,CANCER,LEO,VIRGO,LIBRA,SCORPIO,SAGITTARIUS,CAPRICORN,AQUARIUS,PISCES}
public enum Element{NONE,RED,BLUE,GREEN,YELLOW,WHITE,PURPLE}
public enum Sin{PRIDE,WRATH,ENVY,GREED,LUST,SLOTH,GLUTTONY}

public enum BeastClass
{
    COMMON,BASTION,MILITARY,CLERGY,SODOMITE,KNIGHT,AVIAN,WHIMSICAL,PEASANT,OUTCAST,BARBARIAN,ARTISIAN,ARCHER,MUSICIAN,ARISTOCRAT,
    UNDEAD,TRICKSTER,OCCULT,NAVAL,BELL,DUELIST

    
}

